### ISSUE TITLE
Enhancement Request - Color shade reflecting nature of object - Executable vs Data (input/output)

### ISSUE THREAD

**Issue by ericmarceau-rogers** [arkanis/process-map#4]
This one might be a stretch.

Not sure if there is a practical way to reflect the distinction of Executable vs Data, within a same "block" representing an object.

If I am not mistaken, if the full grouping for a given PID is at level 1, then the distinction would only be applicable to the elements displayed at level 2, which would be the first level of breakdown/division of all memory associated with a given process.

Maybe you are already doing this and I don't realize it.

**Comment by arkanis** [comment]
Right now the color is based on the name of the memory mapping. For mappings backed by a file this is the path to the file, but there are also other named mappings like "[stack]". Unmapped areas or anonymous mappings are drawn in two different shades of light gray.

Each mapping also has a permission mask,  e.g. "rw-p" or "r-xp" which is shown at the top of the window. If you're interested in executalbe code vs. data this is your best bet. At least on a superficial level this could be used to color ranges differently. Reserve green hues for read-only mappings, blue hues for writable mappings and red hues for executable mappings. Or something like that.

In the code that would probably require some fiddling with the "color" of the ranges. There the alpha value encodes what type a range is and the fragment shader then looks at that value to come up with a color to draw. Looking at the code right now and it actually looks like a straight forward thing… done it in commit cbeeab6. The color scheme isn't perfect but should be good enough I think.

**Comment by ericmarceau-rogers** [comment]
Thank you for taking the time to explain the logic behind the code, and for implementing as you did.  It is much appreciated.
